# Windows CI with AppVeyor.com
#
# https://www.appveyor.com/docs/lang/ruby/
# https://www.appveyor.com/docs/build-environment/#ruby

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: "24-x64"
    - RUBY_VERSION: "24"
    - RUBY_VERSION: "23-x64"
    - RUBY_VERSION: "23"
    - RUBY_VERSION: "22-x64"
    - RUBY_VERSION: "22"
    - RUBY_VERSION: "21-x64"
    - RUBY_VERSION: "21"
    - RUBY_VERSION: "200-x64"
    - RUBY_VERSION: "200"

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
